/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['LoginRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            /** @description refreshToken cookie: HttpOnly; SameSite=Strict; Path=/api/v1/auth; Secure outside Development. */
            'Set-Cookie'?: unknown
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AuthResponse']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            /** @description refreshToken cookie: HttpOnly; SameSite=Strict; Path=/api/v1/auth; Secure outside Development. */
            'Set-Cookie'?: unknown
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AuthResponse']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            /** @description refreshToken cookie: HttpOnly; SameSite=Strict; Path=/api/v1/auth; Secure outside Development. */
            'Set-Cookie'?: unknown
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AuthUser']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/categories': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          page?: number | string
          pageSize?: number | string
          scope?: components['schemas']['CategoryScope']
          includeInactive?: boolean
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['PagedResponseOfCategoryDto']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CategoryRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CategoryDto']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/categories/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CategoryDto']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CategoryRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CategoryDto']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/units': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          page?: number | string
          pageSize?: number | string
          includeInactive?: boolean
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['PagedResponseOfUnitDto']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['UnitRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['UnitDto']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/units/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['UnitDto']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['UnitRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['UnitDto']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/products': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          page?: number | string
          pageSize?: number | string
          search?: string
          productType?: components['schemas']['ProductType']
          categoryId?: string
          categoryScope?: components['schemas']['CategoryScope']
          preparationArea?: string
          isActive?: boolean
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['PagedResponseOfProductDto']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['ProductRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ProductDto']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/products/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ProductDto']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['ProductRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ProductDto']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          page?: number | string
          pageSize?: number | string
          search?: string
          role?: string
          active?: boolean
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['PagedResponseOfUserDto']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateUserRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['UserDto']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['UserDto']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateUserRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['UserDto']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/{id}/password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['SetUserPasswordRequest']
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/{id}/activate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/{id}/deactivate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/suppliers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          page?: number | string
          pageSize?: number | string
          search?: string
          isActive?: boolean
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['PagedResponseOfSupplierDto']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['SupplierRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['SupplierDto']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/suppliers/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['SupplierDto']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['SupplierRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['SupplierDto']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/attendance/employees/{employeeId}/check-in': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          employeeId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AttendanceRecordDto']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/attendance/employees/{employeeId}/check-out': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          employeeId: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AttendanceRecordDto']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/attendance/employees/today': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AttendanceTodayResponse']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/attendance/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: {
          from?: string
          to?: string
          page?: number | string
          pageSize?: number | string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AttendancePage']
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/problem+json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    AttendancePage: {
      items: components['schemas']['AttendanceRecordDto'][]
      /** Format: int32 */
      page: number | string
      /** Format: int32 */
      pageSize: number | string
      /** Format: int32 */
      totalCount: number | string
      /** Format: int32 */
      totalPages: number | string
    }
    AttendanceRecordDto: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      employeeId: string
      /** Format: date */
      businessDate: string
      /** Format: date-time */
      checkInAt: string
      checkInByUserId: string
      /** Format: date-time */
      checkOutAt: null | string
      checkOutByUserId: null | string
    }
    AttendanceTodayItem: {
      /** Format: uuid */
      employeeId: string
      fullName: string
      isActive: boolean
      attendanceRecords: components['schemas']['AttendanceRecordDto'][]
      currentState: string
    }
    AttendanceTodayResponse: {
      /** Format: date */
      businessDate: string
      timeZone: string
      items: components['schemas']['AttendanceTodayItem'][]
    }
    AuthResponse: {
      accessToken: string
      /** Format: date-time */
      expiresAt: string
      user: components['schemas']['AuthUser']
    }
    AuthUser: {
      id: string
      username: string
      fullName: null | string
      /** Format: uuid */
      employeeId: null | string
      roles: string[]
    }
    CategoryDto: {
      /** Format: uuid */
      id: string
      name: string
      scope: components['schemas']['CategoryScope']
      isActive: boolean
    }
    CategoryRequest: {
      name: string
      scope: components['schemas']['CategoryScope']
    }
    /** @enum {unknown} */
    CategoryScope: 'MENU' | 'INVENTORY' | 'PREPARATION'
    CreateUserRequest: {
      fullName: string
      username: string
      roles: string[]
    }
    LoginRequest: {
      username?: string
      password?: string
    }
    PagedResponseOfCategoryDto: {
      items: components['schemas']['CategoryDto'][]
      /** Format: int32 */
      page: number | string
      /** Format: int32 */
      pageSize: number | string
      /** Format: int32 */
      totalCount: number | string
      /** Format: int32 */
      totalPages: number | string
    }
    PagedResponseOfProductDto: {
      items: components['schemas']['ProductDto'][]
      /** Format: int32 */
      page: number | string
      /** Format: int32 */
      pageSize: number | string
      /** Format: int32 */
      totalCount: number | string
      /** Format: int32 */
      totalPages: number | string
    }
    PagedResponseOfSupplierDto: {
      items: components['schemas']['SupplierDto'][]
      /** Format: int32 */
      page: number | string
      /** Format: int32 */
      pageSize: number | string
      /** Format: int32 */
      totalCount: number | string
      /** Format: int32 */
      totalPages: number | string
    }
    PagedResponseOfUnitDto: {
      items: components['schemas']['UnitDto'][]
      /** Format: int32 */
      page: number | string
      /** Format: int32 */
      pageSize: number | string
      /** Format: int32 */
      totalCount: number | string
      /** Format: int32 */
      totalPages: number | string
    }
    PagedResponseOfUserDto: {
      items: components['schemas']['UserDto'][]
      /** Format: int32 */
      page: number | string
      /** Format: int32 */
      pageSize: number | string
      /** Format: int32 */
      totalCount: number | string
      /** Format: int32 */
      totalPages: number | string
    }
    ProblemDetails: {
      type?: null | string
      title?: null | string
      /** Format: int32 */
      status?: null | number | string
      detail?: null | string
      instance?: null | string
    }
    ProductDto: {
      /** Format: uuid */
      id: string
      name: string
      productType: components['schemas']['ProductType']
      /** Format: uuid */
      categoryId: null | string
      categoryScope: null | components['schemas']['CategoryScope']
      preparationArea: null | string
      /** Format: uuid */
      inventoryUnitId: string
      /** Format: double */
      salePrice: null | number | string
      /** Format: double */
      minStock: null | number | string
      isActive: boolean
      /** Format: date-time */
      createdAt: string
      createdByUserId: string
      /** Format: date-time */
      updatedAt: string
      updatedByUserId: string
    }
    ProductRequest: {
      name: string
      productType: components['schemas']['ProductType']
      /** Format: uuid */
      categoryId: null | string
      preparationArea: null | string
      /** Format: uuid */
      inventoryUnitId: string
      /** Format: double */
      salePrice: null | number | string
      /** Format: double */
      minStock: null | number | string
    }
    /** @enum {unknown} */
    ProductType: 'INGREDIENT' | 'PREPARATION' | 'SALE_ITEM' | 'SUPPLY'
    SetUserPasswordRequest: {
      newPassword: string
    }
    SupplierDto: {
      /** Format: uuid */
      id: string
      name: string
      phoneNumber: string
      email: null | string
      notes: null | string
      isActive: boolean
      /** Format: date-time */
      createdAt: string
      createdByUserId: string
      /** Format: date-time */
      updatedAt: string
      updatedByUserId: string
    }
    SupplierRequest: {
      name: string
      phoneNumber: string
      email: null | string
      notes: null | string
    }
    /** @enum {unknown} */
    UnitDimension: 'MASS' | 'VOLUME' | 'COUNT'
    UnitDto: {
      /** Format: uuid */
      id: string
      code: string
      name: string
      symbol: string
      dimension: components['schemas']['UnitDimension']
      /** Format: double */
      factor_to_base: number | string
      is_base: boolean
      is_active: boolean
    }
    UnitRequest: {
      code: string
      name: string
      symbol: string
      dimension: components['schemas']['UnitDimension']
      /** Format: double */
      factor_to_base: number | string
      is_base: boolean
    }
    UpdateUserRequest: {
      fullName: string
      username: string
      roles: string[]
    }
    UserDto: {
      id: string
      /** Format: uuid */
      employeeId: string
      fullName: string
      username: string
      roles: string[]
      isActive: boolean
      hasPassword: boolean
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
