using System.Text.Json.Serialization;
using RestaurantSystem.Domain.Catalog;
namespace RestaurantSystem.Application.Catalog;
public sealed record PagedResponse<T>(IReadOnlyList<T> Items, int Page, int PageSize, int TotalCount, int TotalPages);
public sealed record CategoryDto(Guid Id, string Name, CategoryScope Scope, bool IsActive);
public sealed record CategoryRequest(string Name, CategoryScope Scope);
public sealed record UnitDto(Guid Id, string Code, string Name, string Symbol, UnitDimension Dimension, [property: JsonPropertyName("factor_to_base")] decimal FactorToBase, [property: JsonPropertyName("is_base")] bool IsBase, [property: JsonPropertyName("is_active")] bool IsActive);
public sealed record UnitRequest(string Code, string Name, string Symbol, UnitDimension Dimension, [property: JsonPropertyName("factor_to_base")] decimal FactorToBase, [property: JsonPropertyName("is_base")] bool IsBase);
public sealed record ProductDto(Guid Id, string Name, ProductType ProductType, Guid? CategoryId, CategoryScope? CategoryScope, string? PreparationArea, Guid InventoryUnitId, decimal? SalePrice, decimal? MinStock, bool IsSellable, bool IsActive, DateTimeOffset CreatedAt, string CreatedByUserId, DateTimeOffset UpdatedAt, string UpdatedByUserId);
public sealed record ProductRequest(string Name, ProductType ProductType, Guid? CategoryId, string? PreparationArea, Guid InventoryUnitId, decimal? SalePrice, decimal? MinStock, bool IsSellable = false);
public interface ICatalogService {
 Task<PagedResponse<CategoryDto>> Categories(int page, int pageSize, CategoryScope? scope, bool includeInactive, CancellationToken ct); Task<CategoryDto?> Category(Guid id, CancellationToken ct); Task<(CategoryDto? Value,string? Error)> CreateCategory(CategoryRequest r,CancellationToken ct); Task<(CategoryDto? Value,string? Error)> UpdateCategory(Guid id,CategoryRequest r,CancellationToken ct); Task<string?> DeleteCategory(Guid id,CancellationToken ct);
 Task<PagedResponse<UnitDto>> Units(int page,int pageSize,bool includeInactive,CancellationToken ct); Task<UnitDto?> Unit(Guid id,CancellationToken ct); Task<(UnitDto? Value,string? Error)> CreateUnit(UnitRequest r,CancellationToken ct); Task<(UnitDto? Value,string? Error)> UpdateUnit(Guid id,UnitRequest r,CancellationToken ct); Task<string?> DeleteUnit(Guid id,CancellationToken ct);
 Task<PagedResponse<ProductDto>> Products(int page,int pageSize,string? search,ProductType? productType,Guid? categoryId,CategoryScope? categoryScope,string? preparationArea,bool? isActive,CancellationToken ct); Task<ProductDto?> Product(Guid id,CancellationToken ct); Task<(ProductDto? Value,string? Error)> CreateProduct(ProductRequest r,string actor,CancellationToken ct); Task<(ProductDto? Value,string? Error)> UpdateProduct(Guid id,ProductRequest r,string actor,CancellationToken ct); Task<string?> DeleteProduct(Guid id,CancellationToken ct); }
