using System.Security.Claims;
using RestaurantSystem.Application.Operations;
using RestaurantSystem.Application.Catalog;
using RestaurantSystem.Domain.Operations;

public static class OperationsEndpoints
{
 public static void MapOperations(this WebApplication app)
 {
  static IResult E(string error, object? shortages = null) => error switch
  {
   "NOT_FOUND" => Results.NotFound(),
   "PURCHASE_SCOPE_FORBIDDEN" => Results.Forbid(),
   "INVALID_REQUEST" or "INVALID_UNIT_CONVERSION" or "INVALID_COMPOSITION_PARENT" => Results.ValidationProblem(new Dictionary<string, string[]> { ["operations"] = [error] }),
   "DUPLICATE_CUSTOMER_IDENTIFIER" => Results.Problem(statusCode: StatusCodes.Status409Conflict, title: "Customer identity conflict", extensions: new Dictionary<string, object?> { ["code"] = error }),
   _ => Results.Problem(statusCode: StatusCodes.Status409Conflict, title: "Operational workflow conflict", extensions: new Dictionary<string, object?> { ["code"] = error, ["shortages"] = shortages })
  };
  const string Problem = "application/problem+json";
  var api = app.MapGroup("/api/v1");
  var customers = api.MapGroup("/customers").RequireAuthorization("CustomerRead");
  customers.MapGet("", async (int page, int pageSize, string? search, bool? isActive, IOperationsService s, CancellationToken ct) => page < 1 || pageSize is < 1 or > 100 ? Results.ValidationProblem(new Dictionary<string, string[]> { ["paging"] = ["page must be 1 and pageSize must be 1-100"] }) : Results.Ok(await s.CustomersAsync(page, pageSize, search, isActive, ct))).Produces<PagedResponse<CustomerDto>>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403);
  customers.MapGet("/{id:guid}", async (Guid id, IOperationsService s, CancellationToken ct) => await s.CustomerAsync(id, ct) is { } customer ? Results.Ok(customer) : Results.NotFound()).Produces<CustomerDto>().ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
  customers.MapPost("", async (CustomerRequest r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.CreateCustomerAsync(r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct); return x.Error is null ? Results.Created($"/api/v1/customers/{x.Value!.Id}", x.Value) : E(x.Error); }).RequireAuthorization("CustomerWrite").Produces<CustomerDto>(201).ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(409);
  customers.MapPut("/{id:guid}", async (Guid id, CustomerRequest r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.UpdateCustomerAsync(id, r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct); return x.Error is null ? Results.Ok(x.Value) : E(x.Error); }).RequireAuthorization("CustomerWrite").Produces<CustomerDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
  customers.MapPost("/{id:guid}/activate", async (Guid id, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => (await s.SetCustomerActiveAsync(id, true, p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct)) is { } error ? E(error) : Results.NoContent()).RequireAuthorization("CustomerStatusManage").Produces(204).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
  customers.MapPost("/{id:guid}/deactivate", async (Guid id, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => (await s.SetCustomerActiveAsync(id, false, p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct)) is { } error ? E(error) : Results.NoContent()).RequireAuthorization("CustomerStatusManage").Produces(204).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
  var products = api.MapGroup("/products");
  products.MapGet("/{id:guid}/composition", async (Guid id, IOperationsService s, CancellationToken ct) => await s.CompositionAsync(id, ct) is { } x ? Results.Ok(x) : Results.NotFound()).RequireAuthorization("CatalogRead").Produces<CompositionDto>().ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
  products.MapPut("/{id:guid}/composition", async (Guid id, IReadOnlyList<CompositionLineRequest> r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.ReplaceCompositionAsync(id, r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct); return x.Error is null ? Results.Ok(x.Value) : E(x.Error); }).RequireAuthorization("CatalogWrite").Produces<CompositionDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
  products.MapPut("/{id:guid}/minimum-stock", async (Guid id, MinimumStockRequest r, IOperationsService s, CancellationToken ct) => { var x = await s.SetMinimumStockAsync(id, r.MinStock, ct); return x.Error is null ? Results.Ok(new { productId = id, minStock = x.Value }) : E(x.Error); }).RequireAuthorization("InventoryManage").Produces(200).ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
  products.MapGet("/{id:guid}/production-requirements", async (Guid id, decimal quantity, IOperationsService s, CancellationToken ct) => { var x = await s.RequirementsAsync(id, quantity, ct); return x.Error is null ? Results.Ok(x.Value) : E(x.Error); }).RequireAuthorization("KitchenManage").Produces<ProductionRequirementsDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
  api.MapPost("/productions", async (CreateProductionRequest r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.ProduceAsync(r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct); return x.Error is null ? Results.Created($"/api/v1/productions/{x.Value!.Id}", x.Value) : E(x.Error); }).RequireAuthorization("KitchenManage").Produces<ProductionDto>(201).ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
  var productions = api.MapGroup("/productions").RequireAuthorization("ProductionHistory");
  productions.MapGet("", async (int page, int pageSize, Guid? productId, string? batchCode, ProductionStatus? status, string? responsible, DateTimeOffset? from, DateTimeOffset? to, IOperationsService s, CancellationToken ct) => page < 1 || pageSize is < 1 or > 100 || from > to ? Results.ValidationProblem(new Dictionary<string, string[]> { ["productions"] = ["Invalid paging or date range"] }) : Results.Ok(await s.ProductionsAsync(page, pageSize, productId, batchCode, status, responsible, from, to, ct))).Produces<PagedResponse<ProductionHistoryDto>>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403);
  productions.MapGet("/summary", async (Guid? productId, string? batchCode, ProductionStatus? status, string? responsible, DateTimeOffset? from, DateTimeOffset? to, IOperationsService s, CancellationToken ct) => from > to ? Results.ValidationProblem(new Dictionary<string, string[]> { ["productions"] = ["Invalid date range"] }) : Results.Ok(await s.ProductionSummaryAsync(productId, batchCode, status, responsible, from, to, ct))).Produces<ProductionSummaryDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403);
  productions.MapGet("/{id:guid}", async (Guid id, IOperationsService s, CancellationToken ct) => await s.ProductionAsync(id, ct) is { } x ? Results.Ok(x) : Results.NotFound()).Produces<ProductionDetailDto>().ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
  var schedules = api.MapGroup("/work-schedules").RequireAuthorization("WorkScheduleManage");
  schedules.MapGet("", async (IOperationsService s, CancellationToken ct) => Results.Ok(await s.WorkSchedulesAsync(ct))).Produces<IReadOnlyList<WorkScheduleDto>>().ProducesProblem(401).ProducesProblem(403);
  schedules.MapPut("/{shiftType}", async (ShiftType shiftType, WorkScheduleRequest r, IOperationsService s, CancellationToken ct) => { var x = await s.UpdateWorkScheduleAsync(shiftType, r, ct); return x.Error is null ? Results.Ok(x.Value) : E(x.Error); }).Produces<WorkScheduleDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
  var shifts = api.MapGroup("/shifts");
  shifts.MapPost("/open", async (OpenOperationalDayRequest? r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.OpenAsync(r ?? new(null, null), p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct); return x.Error is null ? Results.Ok(x.Value) : E(x.Error); }).RequireAuthorization("OperationsShiftManage").Produces<ShiftContextDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(409);
  shifts.MapGet("/current", async (IOperationsService s, CancellationToken ct) => await s.CurrentShiftAsync(ct) is { } x ? Results.Ok(x) : Results.NotFound()).RequireAuthorization("OperationsShiftManage").Produces<ShiftContextDto>().ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
  shifts.MapGet("/me/current", async (ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => await s.MyCurrentShiftAsync(p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct) is { } x ? Results.Ok(x) : Results.NotFound()).RequireAuthorization("OrdersAccess").Produces<ShiftDto>().ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
  shifts.MapPut("/{id:guid}/assignments", async (Guid id, ShiftAssignmentRequest r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.AssignAsync(id, r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct); return x.Error is null ? Results.Ok(x.Value) : E(x.Error); }).RequireAuthorization("OperationsShiftManage").Produces<ShiftDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
  shifts.MapPost("/{id:guid}/handover", async (Guid id, HandoverRequest r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.HandoverAsync(id, r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct); return x.Error is null ? Results.Ok(x.Value) : E(x.Error); }).RequireAuthorization("OperationsShiftManage").Produces<ShiftContextDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
  api.MapPost("/sales", async (ConfirmSaleRequest r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.ConfirmSaleAsync(r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct); return x.Error is null ? Results.Created($"/api/v1/sales/{x.Value!.Id}", x.Value) : E(x.Error, x.Shortages); }).RequireAuthorization("OrdersAccess").Produces<SaleDto>(201).ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409, contentType: Problem);
  var sales = api.MapGroup("/sales").RequireAuthorization("SalesHistory");
  sales.MapGet("", async (int page, int pageSize, DateTimeOffset? from, DateTimeOffset? to, Guid? shiftId, SalesChannel? salesChannel, PaymentMethod? paymentMethod, string? customerSearch, ClaimsPrincipal p, ISalesAuthorizationScope authorization, IOperationsService s, CancellationToken ct) => page < 1 || pageSize is < 1 or > 100 || from > to ? Results.ValidationProblem(new Dictionary<string, string[]> { ["sales"] = ["Invalid paging or date range"] }) : Results.Ok(await s.SalesAsync(await authorization.ResolveAsync(p.FindFirstValue(ClaimTypes.NameIdentifier)!, p.FindAll(ClaimTypes.Role).Select(role => role.Value).ToHashSet(), ct), page, pageSize, from, to, shiftId, salesChannel, paymentMethod, customerSearch, ct))).Produces<PagedResponse<SalesHistoryDto>>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403);
  sales.MapGet("/{id:guid}", async (Guid id, ClaimsPrincipal p, ISalesAuthorizationScope authorization, IOperationsService s, CancellationToken ct) => await s.SaleAsync(await authorization.ResolveAsync(p.FindFirstValue(ClaimTypes.NameIdentifier)!, p.FindAll(ClaimTypes.Role).Select(role => role.Value).ToHashSet(), ct), id, ct) is { } sale ? Results.Ok(sale) : Results.NotFound()).Produces<SalesDetailDto>().ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
  var reports = api.MapGroup("/reports");
  reports.MapGet("/sales", async (DateOnly? from, DateOnly? to, ShiftType? shiftType, SalesChannel? salesChannel, ClaimsPrincipal p, ISalesAuthorizationScope authorization, IOperationsService s, CancellationToken ct) => from > to ? Results.ValidationProblem(new Dictionary<string, string[]> { ["sales"] = ["Invalid date range"] }) : Results.Ok(await s.SalesReportAsync(await authorization.ResolveAsync(p.FindFirstValue(ClaimTypes.NameIdentifier)!, p.FindAll(ClaimTypes.Role).Select(role => role.Value).ToHashSet(), ct), from, to, shiftType, salesChannel, ct))).RequireAuthorization("SalesHistory").Produces<SalesReportDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403);
  reports.MapGet("/inventory", async (IOperationsService s, CancellationToken ct) => Results.Ok(await s.InventoryReportAsync(ct))).RequireAuthorization("InventoryRead").Produces<InventoryReportDto>().ProducesProblem(401).ProducesProblem(403);
  reports.MapGet("/attendance", async (DateOnly? from, DateOnly? to, Guid? employeeId, ShiftType? shiftType, IOperationsService s, CancellationToken ct) => from > to ? Results.ValidationProblem(new Dictionary<string, string[]> { ["attendance"] = ["Invalid date range"] }) : Results.Ok(await s.AttendanceReportAsync(from, to, employeeId, shiftType, ct))).RequireAuthorization("AttendanceAdministrative").Produces<AttendanceReportDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403);
  var purchases = api.MapGroup("/purchases").RequireAuthorization("SupplierRead");
  purchases.MapPost("", async (CreatePurchaseRequest r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.CreatePurchaseAsync(r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, p.FindAll(ClaimTypes.Role).Select(x => x.Value).ToHashSet(), ct); return x.Error is null ? Results.Created($"/api/v1/purchases/{x.Value!.Id}", x.Value) : E(x.Error); }).RequireAuthorization("OperationsPurchase").Produces<PurchaseDto>(201).ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
  purchases.MapGet("", async (int page, int pageSize, PurchaseStatus? status, IOperationsService s, CancellationToken ct) => page < 1 || pageSize is < 1 or > 100 ? Results.ValidationProblem(new Dictionary<string, string[]> { ["purchases"] = ["Invalid paging or date range"] }) : Results.Ok(await s.PurchasesAsync(page, pageSize, status, ct))).Produces<PagedResponse<PurchaseDto>>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403);
  purchases.MapGet("/history", async (int page, int pageSize, PurchaseStatus? status, Guid? supplierId, string? purchaseArea, string? responsible, DateOnly? from, DateOnly? to, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => page < 1 || pageSize is < 1 or > 100 || from > to ? Results.ValidationProblem(new Dictionary<string, string[]> { ["purchases"] = ["Invalid paging or date range"] }) : Results.Ok(await s.PurchaseHistoryAsync(p.FindAll(ClaimTypes.Role).Select(role => role.Value).ToHashSet(), page, pageSize, status, supplierId, purchaseArea, responsible, from, to, ct))).RequireAuthorization("PurchaseHistory").Produces<PagedResponse<PurchaseHistoryDto>>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403);
  purchases.MapGet("/{id:guid}", async (Guid id, IOperationsService s, CancellationToken ct) => await s.PurchaseAsync(id, ct) is { } x ? Results.Ok(x) : Results.NotFound()).Produces<PurchaseDto>().ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
  purchases.MapGet("/history/{id:guid}", async (Guid id, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => await s.PurchaseDetailAsync(p.FindAll(ClaimTypes.Role).Select(role => role.Value).ToHashSet(), id, ct) is { } x ? Results.Ok(x) : Results.NotFound()).RequireAuthorization("PurchaseHistory").Produces<PurchaseDetailDto>().ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
      purchases.MapPost("/{id:guid}/cancel", async (Guid id, CancelPurchaseRequest r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.CancelPurchaseAsync(id, r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, p.FindAll(ClaimTypes.Role).Select(x => x.Value).ToHashSet(), ct); return x.Error is null ? Results.Ok(x.Value) : E(x.Error); }).RequireAuthorization("OperationsPurchase").Produces<PurchaseDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
      purchases.MapPost("/{id:guid}/receive", async (Guid id, ReceivePurchaseRequest r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.ReceivePurchaseAsync(id, r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, p.FindAll(ClaimTypes.Role).Select(x => x.Value).ToHashSet(), ct); return x.Error is null ? Results.Ok(x.Value) : E(x.Error); }).RequireAuthorization("OperationsPurchase").Produces<PurchaseDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
      var cash = api.MapGroup("/cash");
      cash.MapGet("/preview", async (IOperationsService s, CancellationToken ct) => await s.CashPreviewAsync(ct) is { } x ? Results.Ok(x) : Results.NotFound()).RequireAuthorization("CashManage").Produces<CashPreviewDto>().ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
      cash.MapPost("/close", async (CloseCashRequest r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.CloseCashAsync(r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct); return x.Error is null ? Results.Created($"/api/v1/cash/closings/{x.Value!.Id}", x.Value) : E(x.Error); }).RequireAuthorization("CashManage").Produces<CashClosingDto>(201).ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
      cash.MapGet("/closings", async (int page, int pageSize, IOperationsService s, CancellationToken ct) => page < 1 || pageSize is < 1 or > 100 ? Results.ValidationProblem(new Dictionary<string, string[]> { ["paging"] = ["page must be 1 and pageSize must be 1-100"] }) : Results.Ok(await s.CashClosingsAsync(page, pageSize, ct))).RequireAuthorization("CashHistory").Produces<PagedResponse<CashClosingDto>>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403);
      cash.MapGet("/closings/{id:guid}", async (Guid id, IOperationsService s, CancellationToken ct) => await s.CashClosingAsync(id, ct) is { } x ? Results.Ok(x) : Results.NotFound()).RequireAuthorization("CashHistory").Produces<CashClosingDto>().ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
 }
}
