using System.Security.Claims;
using RestaurantSystem.Application.Operations;
using RestaurantSystem.Application.Catalog;
using RestaurantSystem.Domain.Operations;

public static class OperationsEndpoints
{
 public static void MapOperations(this WebApplication app)
 {
  static IResult E(string error, object? shortages = null) => error switch
  {
   "NOT_FOUND" => Results.NotFound(),
   "PURCHASE_SCOPE_FORBIDDEN" => Results.Forbid(),
   "INVALID_REQUEST" or "INVALID_UNIT_CONVERSION" or "INVALID_COMPOSITION_PARENT" => Results.ValidationProblem(new Dictionary<string, string[]> { ["operations"] = [error] }),
   _ => Results.Problem(statusCode: StatusCodes.Status409Conflict, title: "Operational workflow conflict", extensions: new Dictionary<string, object?> { ["code"] = error, ["shortages"] = shortages })
  };
  const string Problem = "application/problem+json";
  var api = app.MapGroup("/api/v1");
  var products = api.MapGroup("/products");
  products.MapGet("/{id:guid}/composition", async (Guid id, IOperationsService s, CancellationToken ct) => await s.CompositionAsync(id, ct) is { } x ? Results.Ok(x) : Results.NotFound()).RequireAuthorization("CatalogRead").Produces<CompositionDto>().ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
  products.MapPut("/{id:guid}/composition", async (Guid id, IReadOnlyList<CompositionLineRequest> r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.ReplaceCompositionAsync(id, r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct); return x.Error is null ? Results.Ok(x.Value) : E(x.Error); }).RequireAuthorization("CatalogWrite").Produces<CompositionDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
  products.MapPut("/{id:guid}/minimum-stock", async (Guid id, MinimumStockRequest r, IOperationsService s, CancellationToken ct) => { var x = await s.SetMinimumStockAsync(id, r.MinStock, ct); return x.Error is null ? Results.Ok(new { productId = id, minStock = x.Value }) : E(x.Error); }).RequireAuthorization("InventoryManage").Produces(200).ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
  products.MapGet("/{id:guid}/production-requirements", async (Guid id, decimal quantity, IOperationsService s, CancellationToken ct) => { var x = await s.RequirementsAsync(id, quantity, ct); return x.Error is null ? Results.Ok(x.Value) : E(x.Error); }).RequireAuthorization("KitchenManage").Produces<ProductionRequirementsDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
  api.MapPost("/productions", async (CreateProductionRequest r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.ProduceAsync(r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct); return x.Error is null ? Results.Created($"/api/v1/productions/{x.Value!.Id}", x.Value) : E(x.Error); }).RequireAuthorization("KitchenManage").Produces<ProductionDto>(201).ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
  var shifts = api.MapGroup("/shifts");
  shifts.MapPost("/open", async (ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.OpenAsync(p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct); return x.Error is null ? Results.Ok(x.Value) : E(x.Error); }).RequireAuthorization("OperationsShiftManage").Produces<ShiftContextDto>().ProducesProblem(401).ProducesProblem(403).ProducesProblem(409);
  shifts.MapGet("/current", async (IOperationsService s, CancellationToken ct) => await s.CurrentShiftAsync(ct) is { } x ? Results.Ok(x) : Results.NotFound()).RequireAuthorization("OperationsShiftManage").Produces<ShiftContextDto>().ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
  shifts.MapGet("/me/current", async (ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => await s.MyCurrentShiftAsync(p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct) is { } x ? Results.Ok(x) : Results.NotFound()).RequireAuthorization("OrdersAccess").Produces<ShiftDto>().ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
  shifts.MapPut("/{id:guid}/assignments", async (Guid id, ShiftAssignmentRequest r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.AssignAsync(id, r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct); return x.Error is null ? Results.Ok(x.Value) : E(x.Error); }).RequireAuthorization("OperationsShiftManage").Produces<ShiftDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
  shifts.MapPost("/{id:guid}/handover", async (Guid id, HandoverRequest r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.HandoverAsync(id, r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct); return x.Error is null ? Results.Ok(x.Value) : E(x.Error); }).RequireAuthorization("OperationsShiftManage").Produces<ShiftContextDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
  api.MapPost("/sales", async (ConfirmSaleRequest r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.ConfirmSaleAsync(r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, ct); return x.Error is null ? Results.Created($"/api/v1/sales/{x.Value!.Id}", x.Value) : E(x.Error, x.Shortages); }).RequireAuthorization("OrdersAccess").Produces<SaleDto>(201).ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409, contentType: Problem);
  var purchases = api.MapGroup("/purchases").RequireAuthorization("SupplierRead");
  purchases.MapPost("", async (CreatePurchaseRequest r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.CreatePurchaseAsync(r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, p.FindAll(ClaimTypes.Role).Select(x => x.Value).ToHashSet(), ct); return x.Error is null ? Results.Created($"/api/v1/purchases/{x.Value!.Id}", x.Value) : E(x.Error); }).RequireAuthorization("OperationsPurchase").Produces<PurchaseDto>(201).ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
  purchases.MapGet("/{id:guid}", async (Guid id, IOperationsService s, CancellationToken ct) => await s.PurchaseAsync(id, ct) is { } x ? Results.Ok(x) : Results.NotFound()).Produces<PurchaseDto>().ProducesProblem(401).ProducesProblem(403).ProducesProblem(404);
  purchases.MapGet("", async (int page, int pageSize, PurchaseStatus? status, IOperationsService s, CancellationToken ct) => page < 1 || pageSize is < 1 or > 100 ? Results.ValidationProblem(new Dictionary<string, string[]> { ["paging"] = ["page must be 1 and pageSize must be 1-100"] }) : Results.Ok(await s.PurchasesAsync(page, pageSize, status, ct))).Produces<PagedResponse<PurchaseDto>>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403);
  purchases.MapPost("/{id:guid}/cancel", async (Guid id, CancelPurchaseRequest r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.CancelPurchaseAsync(id, r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, p.FindAll(ClaimTypes.Role).Select(x => x.Value).ToHashSet(), ct); return x.Error is null ? Results.Ok(x.Value) : E(x.Error); }).RequireAuthorization("OperationsPurchase").Produces<PurchaseDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
  purchases.MapPost("/{id:guid}/receive", async (Guid id, ReceivePurchaseRequest r, ClaimsPrincipal p, IOperationsService s, CancellationToken ct) => { var x = await s.ReceivePurchaseAsync(id, r, p.FindFirstValue(ClaimTypes.NameIdentifier)!, p.FindAll(ClaimTypes.Role).Select(x => x.Value).ToHashSet(), ct); return x.Error is null ? Results.Ok(x.Value) : E(x.Error); }).RequireAuthorization("OperationsPurchase").Produces<PurchaseDto>().ProducesValidationProblem(400).ProducesProblem(401).ProducesProblem(403).ProducesProblem(404).ProducesProblem(409);
 }
}
