using RestaurantSystem.Domain.Catalog;

namespace RestaurantSystem.Domain.Operations;

public sealed class ProductComposition { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ParentProductId { get; set; } public Guid ComponentProductId { get; set; } public decimal QuantityPerOutputUnit { get; set; } public Guid UnitId { get; set; } public DateTimeOffset CreatedAt { get; set; } public required string CreatedByUserId { get; set; } }
public sealed class Production { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ProductId { get; set; } public decimal QuantityProduced { get; set; } public Guid? ResponsibleEmployeeId { get; set; } public string? Notes { get; set; } public DateTimeOffset ProducedAt { get; set; } public required string CreatedByUserId { get; set; } public List<ProductionConsumption> Consumptions { get; set; } = []; }
public sealed class ProductionConsumption { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ProductionId { get; set; } public Guid ComponentProductId { get; set; } public decimal QuantityConsumed { get; set; } }
public enum ShiftType { MORNING, NIGHT }
public enum ShiftStatus { PENDING, ACTIVE, COMPLETED }
public sealed class CashSession { public Guid Id { get; set; } = Guid.NewGuid(); public DateOnly BusinessDate { get; set; } public bool IsOpen { get; set; } = true; public DateTimeOffset OpenedAt { get; set; } public required string OpenedByUserId { get; set; } public List<Shift> Shifts { get; set; } = []; }
public sealed class Shift { public Guid Id { get; set; } = Guid.NewGuid(); public Guid CashSessionId { get; set; } public ShiftType Type { get; set; } public ShiftStatus Status { get; set; } = ShiftStatus.PENDING; public DateTimeOffset? StartedAt { get; set; } public DateTimeOffset? EndedAt { get; set; } public string? HandoverNote { get; set; } public List<ShiftAssignment> Assignments { get; set; } = []; }
public sealed class ShiftAssignment { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ShiftId { get; set; } public Guid EmployeeId { get; set; } public DateTimeOffset AssignedAt { get; set; } public required string AssignedByUserId { get; set; } }
public enum SalesChannel { DIRECT, PEDIDOSYA }
public enum PaymentMethod { CASH, QR, EXTERNAL }
public sealed class Sale { public Guid Id { get; set; } = Guid.NewGuid(); public Guid OrderId { get; set; } public Guid ShiftId { get; set; } public SalesChannel SalesChannel { get; set; } public PaymentMethod PaymentMethod { get; set; } public decimal Subtotal { get; set; } public decimal Total { get; set; } public DateTimeOffset ConfirmedAt { get; set; } public required string ConfirmedByUserId { get; set; } public List<SaleItem> Items { get; set; } = []; }
public sealed class SaleItem { public Guid Id { get; set; } = Guid.NewGuid(); public Guid SaleId { get; set; } public Guid OrderItemId { get; set; } public Guid ProductId { get; set; } public decimal Quantity { get; set; } public decimal UnitPrice { get; set; } public decimal LineTotal { get; set; } }
public enum PurchaseStatus { PENDIENTE, RECIBIDA, CANCELADA }
public sealed class Purchase { public Guid Id { get; set; } = Guid.NewGuid(); public Guid SupplierId { get; set; } public PurchaseStatus Status { get; set; } = PurchaseStatus.PENDIENTE; public DateOnly PurchaseDate { get; set; } public decimal Total { get; set; } public string? ReceiptReference { get; set; } public string? Notes { get; set; } public string? CancellationReason { get; set; } public DateTimeOffset? CancelledAt { get; set; } public string? CancelledByUserId { get; set; } public DateTimeOffset CreatedAt { get; set; } public required string CreatedByUserId { get; set; } public List<PurchaseItem> Items { get; set; } = []; }
public sealed class PurchaseItem { public Guid Id { get; set; } = Guid.NewGuid(); public Guid PurchaseId { get; set; } public Guid ProductId { get; set; } public decimal Quantity { get; set; } public Guid UnitId { get; set; } public decimal UnitCost { get; set; } public decimal LineTotal { get; set; } }
public sealed class PurchaseReceipt { public Guid Id { get; set; } = Guid.NewGuid(); public Guid PurchaseId { get; set; } public DateTimeOffset ReceivedAt { get; set; } public required string ReceivedByUserId { get; set; } public string? Notes { get; set; } public List<PurchaseReceiptLine> Lines { get; set; } = []; }
public sealed class PurchaseReceiptLine { public Guid Id { get; set; } = Guid.NewGuid(); public Guid PurchaseReceiptId { get; set; } public Guid PurchaseItemId { get; set; } public decimal ReceivedQuantity { get; set; } public Guid UnitId { get; set; } }
