using Microsoft.EntityFrameworkCore;
using RestaurantSystem.Application.Catalog;
using RestaurantSystem.Domain.Catalog;
namespace RestaurantSystem.Infrastructure.Catalog;
public sealed class CatalogService(ApplicationDbContext db) : ICatalogService
{
 static readonly HashSet<string> CanonicalCodes = ["g","kg","ml","l","unit"];
 static bool Invalid(string? s) => string.IsNullOrWhiteSpace(s);
 static CategoryDto C(Category x) => new(x.Id,x.Name,x.Scope,x.IsActive); static UnitDto U(Unit x) => new(x.Id,x.Code,x.Name,x.Symbol,x.Dimension,x.FactorToBase,x.IsBase,x.IsActive); static ProductDto P(Product x) => new(x.Id,x.Name,x.ProductType,x.CategoryId,x.Category?.Scope,x.PreparationArea,x.InventoryUnitId,x.SalePrice,x.MinStock,x.IsSellable,x.IsActive,x.CreatedAt,x.CreatedByUserId,x.UpdatedAt,x.UpdatedByUserId);
 static async Task<PagedResponse<T>> Page<T>(IQueryable<T> q,int page,int size,CancellationToken ct) { var count=await q.CountAsync(ct); return new(await q.Skip((page-1)*size).Take(size).ToListAsync(ct),page,size,count,(int)Math.Ceiling(count/(double)size)); }
 public Task<PagedResponse<CategoryDto>> Categories(int page,int size,CategoryScope? scope,bool inactive,CancellationToken ct) { var q=db.Categories.AsNoTracking().Where(x=>inactive||x.IsActive); if(scope is not null)q=q.Where(x=>x.Scope==scope); return Page(q.OrderBy(x=>x.Name).Select(x=>C(x)),page,size,ct); }
 public async Task<CategoryDto?> Category(Guid id,CancellationToken ct) { var x=await db.Categories.FindAsync([id],ct); return x is null?null:C(x); }
 public async Task<(CategoryDto?,string?)> CreateCategory(CategoryRequest r,CancellationToken ct) { if(Invalid(r.Name))return(null,"Invalid category"); var name=r.Name.Trim(); if(await db.Categories.AnyAsync(x=>x.Scope==r.Scope&&x.Name.ToLower()==name.ToLower(),ct))return(null,"Duplicate category"); var x=new Category{Name=name,Scope=r.Scope};db.Categories.Add(x);await db.SaveChangesAsync(ct);return(C(x),null); }
 public async Task<(CategoryDto?,string?)> UpdateCategory(Guid id,CategoryRequest r,CancellationToken ct) { var x=await db.Categories.FindAsync([id],ct);if(x is null)return(null,"Not found");if(Invalid(r.Name))return(null,"Invalid category");var name=r.Name.Trim();if(await db.Categories.AnyAsync(y=>y.Id!=id&&y.Scope==r.Scope&&y.Name.ToLower()==name.ToLower(),ct))return(null,"Duplicate category");x.Name=name;x.Scope=r.Scope;await db.SaveChangesAsync(ct);return(C(x),null); }
 public async Task<string?> DeleteCategory(Guid id,CancellationToken ct) { var x=await db.Categories.FindAsync([id],ct);if(x is null)return"Not found";if(await db.Products.AnyAsync(p=>p.CategoryId==id,ct))return"Category is in use";x.IsActive=false;await db.SaveChangesAsync(ct);return null; }
 public Task<PagedResponse<UnitDto>> Units(int page,int size,bool inactive,CancellationToken ct)=>Page(db.Units.AsNoTracking().Where(x=>inactive||x.IsActive).OrderBy(x=>x.Code).Select(x=>U(x)),page,size,ct);
 public async Task<UnitDto?> Unit(Guid id,CancellationToken ct){var x=await db.Units.FindAsync([id],ct);return x is null?null:U(x);}
 async Task<string?> ValidateUnit(UnitRequest r,Guid? ignore,CancellationToken ct){if(Invalid(r.Code)||Invalid(r.Name)||Invalid(r.Symbol)||r.FactorToBase<=0||(r.IsBase&&r.FactorToBase!=1))return"Invalid unit";if(await db.Units.AnyAsync(x=>x.Id!=ignore&&x.Code.ToLower()==r.Code.Trim().ToLower(),ct))return"Duplicate unit code";if(r.IsBase&&await db.Units.AnyAsync(x=>x.Id!=ignore&&x.Dimension==r.Dimension&&x.IsBase&&x.IsActive,ct))return"Dimension already has a base unit";return null;}
 public async Task<(UnitDto?,string?)> CreateUnit(UnitRequest r,CancellationToken ct){var error=await ValidateUnit(r,null,ct);if(error is not null)return(null,error);var x=new Unit{Code=r.Code.Trim(),Name=r.Name.Trim(),Symbol=r.Symbol.Trim(),Dimension=r.Dimension,FactorToBase=r.FactorToBase,IsBase=r.IsBase};db.Units.Add(x);await db.SaveChangesAsync(ct);return(U(x),null);}
 public async Task<(UnitDto?,string?)> UpdateUnit(Guid id,UnitRequest r,CancellationToken ct){var x=await db.Units.FindAsync([id],ct);if(x is null)return(null,"Not found");if(CanonicalCodes.Contains(x.Code, StringComparer.OrdinalIgnoreCase)&&(x.Code!=r.Code||x.Dimension!=r.Dimension||x.FactorToBase!=r.FactorToBase||x.IsBase!=r.IsBase))return(null,"Canonical unit is protected");if(x.IsBase && !r.IsBase)return(null,"Active base unit is protected");var error=await ValidateUnit(r,id,ct);if(error is not null)return(null,error);x.Code=r.Code.Trim();x.Name=r.Name.Trim();x.Symbol=r.Symbol.Trim();x.Dimension=r.Dimension;x.FactorToBase=r.FactorToBase;x.IsBase=r.IsBase;await db.SaveChangesAsync(ct);return(U(x),null);}
 public async Task<string?> DeleteUnit(Guid id,CancellationToken ct){var x=await db.Units.FindAsync([id],ct);if(x is null)return"Not found";if(CanonicalCodes.Contains(x.Code, StringComparer.OrdinalIgnoreCase)||x.IsBase||await db.Products.AnyAsync(p=>p.InventoryUnitId==id,ct))return"Unit is protected or in use";x.IsActive=false;await db.SaveChangesAsync(ct);return null;}
 public Task<PagedResponse<ProductDto>> Products(int page,int size,string? search,ProductType? type,Guid? categoryId,CategoryScope? scope,string? area,bool? active,CancellationToken ct){var q=db.Products.AsNoTracking().Include(x=>x.Category).AsQueryable();if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.Name.ToLower().Contains(search.ToLower()));if(type is not null)q=q.Where(x=>x.ProductType==type);if(categoryId is not null)q=q.Where(x=>x.CategoryId==categoryId);if(scope is not null)q=q.Where(x=>x.Category!.Scope==scope);if(!string.IsNullOrWhiteSpace(area))q=q.Where(x=>x.PreparationArea==area);q=q.Where(x=>x.IsActive==(active??true));return Page(q.OrderBy(x=>x.Name).Select(x=>P(x)),page,size,ct);}
 public async Task<ProductDto?> Product(Guid id,CancellationToken ct){var x=await db.Products.Include(x=>x.Category).SingleOrDefaultAsync(x=>x.Id==id,ct);return x is null?null:P(x);}
 async Task<string?> ValidateProduct(ProductRequest r,CancellationToken ct){if(Invalid(r.Name)||r.SalePrice<0||r.MinStock<0)return"Invalid product";if(!await db.Units.AnyAsync(x=>x.Id==r.InventoryUnitId&&x.IsActive,ct))return"Not found";if(r.CategoryId is not null&&!await db.Categories.AnyAsync(x=>x.Id==r.CategoryId&&x.IsActive,ct))return"Not found";return null;}
 public async Task<(ProductDto?,string?)> CreateProduct(ProductRequest r,string actor,CancellationToken ct){var e=await ValidateProduct(r,ct);if(e is not null)return(null,e);var now=DateTimeOffset.UtcNow;var x=new Product{Name=r.Name.Trim(),ProductType=r.ProductType,CategoryId=r.CategoryId,InventoryUnitId=r.InventoryUnitId,PreparationArea=r.PreparationArea?.Trim(),SalePrice=r.SalePrice,MinStock=r.MinStock,IsSellable=r.IsSellable,CreatedAt=now,UpdatedAt=now,CreatedByUserId=actor,UpdatedByUserId=actor};db.Products.Add(x);await db.SaveChangesAsync(ct);return(await Product(x.Id,ct),null);}
 public async Task<(ProductDto?,string?)> UpdateProduct(Guid id,ProductRequest r,string actor,CancellationToken ct){var x=await db.Products.FindAsync([id],ct);if(x is null)return(null,"Not found");var e=await ValidateProduct(r,ct);if(e is not null)return(null,e);x.Name=r.Name.Trim();x.ProductType=r.ProductType;x.CategoryId=r.CategoryId;x.InventoryUnitId=r.InventoryUnitId;x.PreparationArea=r.PreparationArea?.Trim();x.SalePrice=r.SalePrice;x.MinStock=r.MinStock;x.IsSellable=r.IsSellable;x.UpdatedAt=DateTimeOffset.UtcNow;x.UpdatedByUserId=actor;await db.SaveChangesAsync(ct);return(await Product(id,ct),null);}
 public async Task<string?> DeleteProduct(Guid id,CancellationToken ct){var x=await db.Products.FindAsync([id],ct);if(x is null)return"Not found";x.IsActive=false;await db.SaveChangesAsync(ct);return null;}
}
